name: Virginias Petals CI

on:
  push:
    branches:
      - main
      - elena

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Make gradlew executable
        run: chmod +x ./auth-service/gradlew

      - name: Build and push images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          for dir in */; do
            cd $dir
            for dockerfile in $(find . -type f -name "Dockerfile"); do
              tag="virginia-$(basename $dir)"
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$tag:latest -f $dockerfile .
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/$tag:latest
            done
            cd ..
          done
