name: Virginias Petals CI/CD

on:
  push:
    branches:
      - main
      - elena

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Make gradlew executable
        run: chmod +x ./auth-service/gradlew

      - name: Build and push images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          for dir in */; do
            cd $dir
            for dockerfile in $(find . -type f -name "Dockerfile"); do
              tag="virginia-$(basename $dir)"
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$tag:latest -f $dockerfile .
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/$tag:latest
            done
            cd ..
          done

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    env:
      MASTER_IP: ip172-18-0-90-chicu6o1k7jg00amallg@direct.labs.play-with-docker.com
      WEBHOOK: http://ip172-18-0-90-chicu6o1k7jg00amallg-9000.direct.labs.play-with-docker.com/api/stacks/webhooks/536e2cce-b284-454b-b009-0159b3287ec4

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install & update cURL
        run: sudo apt-get update && sudo apt-get -y install curl

      - name: Deploy to Play With Docker
        run: curl -X POST ${{ env.WEBHOOK }}
